#!/usr/bin/env python3

from esptest import *

#node0 has 2x ds18b20. values are send to domoticz mqtt

espeasy[0].controller_domoticz_mqtt(index=1, controllerip=config.mqtt_broker)
espeasy[0].device_p004(index=1, taskdevicepin1=2, plugin_004_dev=0, plugin_004_res=9, TDID1=1417)
espeasy[0].device_p004(index=2, taskdevicepin1=2, plugin_004_dev=1, plugin_004_res=9, TDID1=1418)


# check mqtt results
temp1=mqtt_expect_json("domoticz/in", {  'idx': 1417 }, timeout=10)
temp2=mqtt_expect_json("domoticz/in", {  'idx': 1418 }, timeout=10)

if float(temp1['svalue'])>0 and float(temp1['svalue'])<40 and float(temp2['svalue'])>0 and float(temp2['svalue'])<40:

    #FIXME:
    log.info("passed")
else:
    raise(Exception("Test failed"))
