#!/usr/bin/env python3

from esptest import *

# hardware requirements:
# - node 0
# - DHT22 on D3

# tests:
# - correct values are send to domoticz via mqtt


@step
def prepare():
    node[0].reboot()
    node[0].pingserial()
    node[0].serialcmd("resetFlashWriteCounter")
    espeasy[0].controller_domoticz_mqtt(index=1, controllerip=config.mqtt_broker)
    espeasy[0].device_p005(index=1, TDID1=4001)


@step
def test():
    results=controller.recv_domoticz_mqtt(SENSOR_TYPE_TEMP_HUM,4001)
    test_in_range(results[0], -5,40)
    test_in_range(results[1], 10,80)
