#!/usr/bin/env python3

from esptest import *

### preprare
# espeasy1=EspEasy(Node(config.nodes[0]))
# espeasy2=EspEasy(Node(config.nodes[1]))



espeasy[1].controller_domoticz_mqtt(index=1, controllerip=config.mqtt_broker)
espeasy[1].device_p001(index=1, taskdevicepin1=12, plugin_001_type=1, plugin_001_button=0, TDID1=1415)



### test
espeasy[0].control(cmd="gpio,12,1")
time.sleep(1)
espeasy[0].control(cmd="gpio,12,0")
time.sleep(1)

# check mqtt results
for message in mqtt_messages:
    payload=json.loads(message.payload.decode())
    if message.topic == 'domoticz/in' and payload['idx']==1415 and payload['switchcmd']=='Off' and payload['command']=='switchlight':
        log.info("all tests ok")
        sys.exit(0)
        #FIXME: this need to be callable, to run a batch of tests at once


raise(Exception("Test failed"))
