#!/usr/bin/env python3

from esptest import *

# hardware requirements:
# - node 0
# - framed oled display connected to default I2C

# tests:
# - only configures it, nothing is verfied yet

espeasy[0].device_p036(index=1)
