#!/usr/bin/env python3

from esptest import *

# hardware requirements:
# - node 0
# - 2x ds18b12 connected to D4

# tests:
# - correct values are send to domoticz via http
# - correct values are send to domoticz via mqtt
# - test if powercycle value is valid (https://github.com/letscontrolit/ESPEasy/issues/719)

# espeasy[0].controller_thingspeak(index=1, controllerip=config.http_server, controllerport=config.http_port)


@step
def prepare_http():
    """configure devices and controller"""
    node[0].reboot()
    node[0].pingserial()
    espeasy[0].controller_domoticz_http(index=1, controllerip=config.http_server, controllerport=config.http_port)
    espeasy[0].device_p004(index=1, taskdevicepin1=2, plugin_004_dev=0, plugin_004_res=9, TDID1=1417)
    espeasy[0].device_p004(index=2, taskdevicepin1=2, plugin_004_dev=1, plugin_004_res=9, TDID1=1418)


@step
def recv_http():
    """wait for http result"""
    results=controller.recv_domoticz_http(SENSOR_TYPE_SINGLE,1417)
    test_in_range(results[0], -5,40)
    results=controller.recv_domoticz_http(SENSOR_TYPE_SINGLE,1418)
    test_in_range(results[0], -5,40)




# @step
# def powercycle():
#     """test result on poweron"""
#     node[0].powercycle()
#     results=controller.recv_domoticz_http(SENSOR_TYPE_SINGLE,1417)
#     test_in_range(results[0], -5,40)
#     results=controller.recv_domoticz_http(SENSOR_TYPE_SINGLE,1418)
#     test_in_range(results[0], -5,40)


@step
def prepare_mqtt():
    """switch to mqtt"""
    espeasy[0].controller_domoticz_mqtt(index=1, controllerip=config.mqtt_broker)


@step
def recv_mqtt():
    """wait for mqtt result"""
    results=controller.recv_domoticz_mqtt(SENSOR_TYPE_SINGLE,1417)
    test_in_range(results[0], -5,40)
    results=controller.recv_domoticz_mqtt(SENSOR_TYPE_SINGLE,1418)
    test_in_range(results[0], -5,40)



run()
