# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
from recommonmark.parser import CommonMarkParser
import sphinx_bootstrap_theme


# -- Project information -----------------------------------------------------

project = u'ESP Easy'
copyright = u'2018, ESP Easy'
author = u'Grovkillen, TD-er & Friends'

# The short X.Y version
version = u''
# The full version, including alpha/beta/rc tags
release = u'2.1-beta1'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.imgmath',
    'sphinx.ext.imgconverter',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_parsers = {
    '.md': CommonMarkParser,
}

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
#source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------
html_logo = 'ESPEasy/espeasy_logo.png'
html_favicon = 'ESPEasy/favicon.ico'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'sphinx_rtd_theme'
html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
#html_theme_options = {
#    'canonical_url': '',
#    'analytics_id': '',
#    'logo_only': False,
#    'display_version': True,
#    'prev_next_buttons_location': 'bottom',
#    'style_external_links': False,
#    # Toc options
#    'collapse_navigation': True,
#    'sticky_navigation': True,
#    'navigation_depth': 4,
#    'includehidden': True,
#    'titles_only': False
#}

html_theme_options = {
    # Navigation bar title. (Default: ``project`` value)
    'navbar_title': "ESP Easy",

    # Tab name for entire site. (Default: "Site")
    'navbar_site_name': "Site",

    # A list of tuples containing pages or urls to link to.
    # Valid tuples should be in the following forms:
    #    (name, page)                 # a link to a page
    #    (name, "/aa/bb", 1)          # a link to an arbitrary relative url
    #    (name, "http://example.com", True) # arbitrary absolute url
    # Note the "1" or "True" value above as the third argument to indicate
    # an arbitrary url.
    'navbar_links': [
        ("Rules", "Rules/Rules"),
        ("Forum", "https://www.letscontrolit.com/forum/viewforum.php?f=1", True),
    ],

    # Render the next and previous page links in navbar. (Default: true)
    'navbar_sidebarrel': True,

    # Render the current pages TOC in the navbar. (Default: true)
    'navbar_pagenav': True,

    # Tab name for the current pages TOC. (Default: "Page")
    'navbar_pagenav_name': "Page",

    # Global TOC depth for "site" navbar tab. (Default: 1)
    # Switching to -1 shows all levels.
    'globaltoc_depth': 2,

    # Include hidden TOCs in Site navbar?
    #
    # Note: If this is "false", you cannot have mixed ``:hidden:`` and
    # non-hidden ``toctree`` directives in the same page, or else the build
    # will break.
    #
    # Values: "true" (default) or "false"
    'globaltoc_includehidden': "false",

    # HTML navbar class (Default: "navbar") to attach to <div> element.
    # For black navbar, do "navbar navbar-inverse"
    'navbar_class': "navbar navbar-inverse",

    # Fix navigation bar to top of page?
    # Values: "true" (default) or "false"
    'navbar_fixed_top': "true",

    # Location of link to source.
    # Options are "nav" (default), "footer" or anything else to exclude.
    'source_link_position': "none",

    # Bootswatch (http://bootswatch.com/) theme.
    #
    # Options are nothing (default) or the name of a valid theme
    # such as "cosmo" or "sandstone".
    #
    # The set of valid themes depend on the version of Bootstrap
    # that's used (the next config option).
    #
    # Currently, the supported themes are:
    # - Bootstrap 2: https://bootswatch.com/2
    # - Bootstrap 3: https://bootswatch.com/3
    'bootswatch_theme': "cerulean",

    # Choose Bootstrap version.
    # Values: "3" (default) or "2" (in quotes)
    'bootstrap_version': "3",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ESPEasydoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ESPEasy.tex', u'ESP Easy Documentation',
     u'Many', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'espeasy', u'ESP Easy Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ESP Easy', u'ESP Easy Documentation',
     author, 'ESP Easy', 'ESP82xx/ESP32 firmware to connect people with any level of experience to system automation.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/3/': None}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# This def is used to add ESP Easy related formatation (color etc).
def setup(app):
    app.add_stylesheet('css/custom.css')

# To replace chunks of text globally +
# ESP Easy colors (set in cutom.css)
rst_prolog = """
.. role:: blue
.. role:: red
.. role:: green
.. role:: yellow
.. role:: orange
.. role:: cyan
.. role:: purple

.. |affiliate| replace:: :yellow:`$` = affiliate links which will give us some money to keep this project running, thank you for using those.

.. |added| replace:: :green:`added`
.. |removed| replace:: :red:`removed`
.. |fixed| replace:: :purple:`fixed`

.. |P000_name| replace:: :cyan:`Internal`
.. |P000_type| replace:: :cyan:`GPIO handling`
.. |P000_typename| replace:: :cyan:`Internal GPIO handling`
.. |P000_status| replace:: :green:`NORMAL`
.. |P000_github| replace:: P001_Switch.ino (will be removed from plugin and added to core)
.. _P000_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P001_Switch.ino
.. |P000_usedby_GPIO| replace:: :ref:`P000_Relay_page`
.. |P000_usedby_RTTTL| replace:: :ref:`P000_Buzzer_page`, :ref:`P000_Piezo_element_page`, :ref:`P000_Speaker_page`
.. |P000_shortinfo| replace:: The ESP module can control things with it's build-in GPIO output pins. We can turn these on or off or we can set these pins to a special pulse modulated value (PWM output). And it's also possible to send short pulses (single pulse) to one of these pins to control specific devices that are switched with a single short high or low signal.
.. |P000_maintainer| replace:: Core
.. |P000_compileinfo| replace:: Currently the GPIO commands are placed in the ``Switch Input - Switch plugin``, this will change!

.. |P001_name| replace:: :cyan:`Switch`
.. |P001_type| replace:: :cyan:`Switch Input`
.. |P001_typename| replace:: :cyan:`Switch Input - Switch`
.. |P001_status| replace:: :green:`NORMAL`
.. |P001_github| replace:: P001_Switch.ino
.. _P001_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P001_Switch.ino
.. |P001_usedby| replace:: `.`
.. |P001_shortinfo| replace:: `.`
.. |P001_maintainer| replace:: `.`
.. |P001_compileinfo| replace:: `.`

.. |P002_name| replace:: :cyan:`Internal`
.. |P002_type| replace:: :cyan:`Analog Input`
.. |P002_typename| replace:: :cyan:`Analog Input - Internal`
.. |P002_status| replace:: :green:`NORMAL`
.. |P002_github| replace:: P002_ADC.ino
.. _P002_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P002_ADC.ino
.. |P002_usedby| replace:: `.`
.. |P002_shortinfo| replace:: `.`
.. |P002_maintainer| replace:: `.`
.. |P002_compileinfo| replace:: `.`

.. |P003_name| replace:: :cyan:`Pulse counter`
.. |P003_type| replace:: :cyan:`Generic`
.. |P003_typename| replace:: :cyan:`Generic - Pulse counter`
.. |P003_status| replace:: :green:`NORMAL`
.. |P003_github| replace:: P003_Pulse.ino
.. _P003_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P003_Pulse.ino
.. |P003_usedby| replace:: `.`
.. |P003_shortinfo| replace:: `.`
.. |P003_maintainer| replace:: `.`
.. |P003_compileinfo| replace:: `.`

.. |P004_name| replace:: :cyan:`DS18b20`
.. |P004_type| replace:: :cyan:`Environment`
.. |P004_typename| replace:: :cyan:`Environment - DS18b20`
.. |P004_status| replace:: :green:`NORMAL`
.. |P004_github| replace:: P004_Dallas.ino
.. _P004_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P004_Dallas.ino
.. |P004_usedby| replace:: `.`
.. |P004_shortinfo| replace:: `.`
.. |P004_maintainer| replace:: `.`
.. |P004_compileinfo| replace:: `.`

.. |P005_name| replace:: :cyan:`DHT11/12/22/SONOFF2301/7021`
.. |P005_type| replace:: :cyan:`Environment`
.. |P005_typename| replace:: :cyan:`Environment - DHT11/12/22/SONOFF2301/7021`
.. |P005_status| replace:: :green:`NORMAL`
.. |P005_github| replace:: P005_DHT.ino
.. _P005_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P005_DHT.ino
.. |P005_usedby| replace:: `.`
.. |P005_shortinfo| replace:: `.`
.. |P005_maintainer| replace:: `.`
.. |P005_compileinfo| replace:: `.`

.. |P006_name| replace:: :cyan:`BMP085/180`
.. |P006_type| replace:: :cyan:`Environment`
.. |P006_typename| replace:: :cyan:`Environment - BMP085/180`
.. |P006_status| replace:: :green:`NORMAL`
.. |P006_github| replace:: P006_BMP085.ino
.. _P006_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P006_BMP085.ino
.. |P006_usedby| replace:: `.`
.. |P006_shortinfo| replace:: `.`
.. |P006_maintainer| replace:: `.`
.. |P006_compileinfo| replace:: `.`

.. |P007_name| replace:: :cyan:`PCF8591`
.. |P007_type| replace:: :cyan:`Analog input`
.. |P007_typename| replace:: :cyan:`Analog input - PCF8591`
.. |P007_status| replace:: :green:`NORMAL`
.. |P007_github| replace:: P007_PCF8591.ino
.. _P007_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P007_PCF8591.ino
.. |P007_usedby| replace:: `.`
.. |P007_shortinfo| replace:: `.`
.. |P007_maintainer| replace:: `.`
.. |P007_compileinfo| replace:: `.`

.. |P008_name| replace:: :cyan:`Wiegand`
.. |P008_type| replace:: :cyan:`RFID`
.. |P008_typename| replace:: :cyan:`RFID - Wiegand`
.. |P008_status| replace:: :green:`NORMAL`
.. |P008_github| replace:: P008_RFID.ino
.. _P008_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P008_RFID.ino
.. |P008_usedby| replace:: `.`
.. |P008_shortinfo| replace:: `.`
.. |P008_maintainer| replace:: `.`
.. |P008_compileinfo| replace:: `.`

.. |P009_name| replace:: :cyan:`MCP23017`
.. |P009_type| replace:: :cyan:`Switch Input`
.. |P009_typename| replace:: :cyan:`Switch Input - MCP23017`
.. |P009_status| replace:: :green:`NORMAL`
.. |P009_github| replace:: P009_MCP.ino
.. _P009_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P009_MCP.ino
.. |P009_usedby| replace:: `.`
.. |P009_shortinfo| replace:: `.`
.. |P009_maintainer| replace:: `.`
.. |P009_compileinfo| replace:: `.`

.. |P010_name| replace:: :cyan:`BH1750`
.. |P010_type| replace:: :cyan:`Light/Lux`
.. |P010_typename| replace:: :cyan:`Light/Lux - BH1750`
.. |P010_status| replace:: :green:`NORMAL`
.. |P010_github| replace:: P010_BH1750.ino
.. _P010_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P010_BH1750.ino
.. |P010_usedby| replace:: `.`
.. |P010_shortinfo| replace:: `.`
.. |P010_maintainer| replace:: `.`
.. |P010_compileinfo| replace:: `.`

.. |P011_name| replace:: :cyan:`ProMini Extender`
.. |P011_type| replace:: :cyan:`Extra IO`
.. |P011_typename| replace:: :cyan:`Extra IO - ProMini Extender`
.. |P011_status| replace:: :green:`NORMAL`
.. |P011_github| replace:: P011_PME.ino
.. _P011_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P011_PME.ino
.. |P011_usedby| replace:: `.`
.. |P011_shortinfo| replace:: `.`
.. |P011_maintainer| replace:: `.`
.. |P011_compileinfo| replace:: `.`

.. |P012_name| replace:: :cyan:`LCD2004`
.. |P012_type| replace:: :cyan:`Display`
.. |P012_typename| replace:: :cyan:`Display - LCD2004`
.. |P012_status| replace:: :green:`NORMAL`
.. |P012_github| replace:: P012_LCD.ino
.. _P012_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P012_LCD.ino
.. |P012_usedby| replace:: `.`
.. |P012_shortinfo| replace:: `.`
.. |P012_maintainer| replace:: `.`
.. |P012_compileinfo| replace:: `.`

.. |P013_name| replace:: :cyan:`HC-SR04/RCW-0001`
.. |P013_type| replace:: :cyan:`Distance`
.. |P013_typename| replace:: :cyan:`Distance - HC-SR04/RCW-0001`
.. |P013_status| replace:: :green:`NORMAL`
.. |P013_github| replace:: P013_HCSR04.ino
.. _P013_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P013_HCSR04.ino
.. |P013_usedby| replace:: `.`
.. |P013_shortinfo| replace:: `.`
.. |P013_maintainer| replace:: `.`
.. |P013_compileinfo| replace:: `.`

.. |P014_name| replace:: :cyan:`SI7021/HTU21D`
.. |P014_type| replace:: :cyan:`Environment`
.. |P014_typename| replace:: :cyan:`Environment - SI7021/HTU21D`
.. |P014_status| replace:: :green:`NORMAL`
.. |P014_github| replace:: P014_SI7021.ino
.. _P014_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P014_SI7021.ino
.. |P014_usedby| replace:: `.`
.. |P014_shortinfo| replace:: `.`
.. |P014_maintainer| replace:: `.`
.. |P014_compileinfo| replace:: `.`

.. |P015_name| replace:: :cyan:`TSL2561`
.. |P015_type| replace:: :cyan:`Light/Lux`
.. |P015_typename| replace:: :cyan:`Light/Lux - TSL2561`
.. |P015_status| replace:: :green:`NORMAL`
.. |P015_github| replace:: P015_TSL2561.ino
.. _P015_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P015_TSL2561.ino
.. |P015_usedby| replace:: `.`
.. |P015_shortinfo| replace:: `.`
.. |P015_maintainer| replace:: `.`
.. |P015_compileinfo| replace:: `.`

.. |P016_name| replace:: :cyan:`TSOP4838`
.. |P016_type| replace:: :cyan:`Communication`
.. |P016_typename| replace:: :cyan:`Communication - TSOP4838`
.. |P016_status| replace:: :green:`NORMAL`
.. |P016_github| replace:: P016_IR.ino
.. _P016_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P016_IR.ino
.. |P016_usedby| replace:: `.`
.. |P016_shortinfo| replace:: `.`
.. |P016_maintainer| replace:: `.`
.. |P016_compileinfo| replace:: `.`

.. |P017_name| replace:: :cyan:`PN532`
.. |P017_type| replace:: :cyan:`RFID`
.. |P017_typename| replace:: :cyan:`RFID - PN532`
.. |P017_status| replace:: :green:`NORMAL`
.. |P017_github| replace:: P017_PN532.ino
.. _P017_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P017_PN532.ino
.. |P017_usedby| replace:: `.`
.. |P017_shortinfo| replace:: `.`
.. |P017_maintainer| replace:: `.`
.. |P017_compileinfo| replace:: `.`

.. |P018_name| replace:: :cyan:`Sharp GP2Y10`
.. |P018_type| replace:: :cyan:`Dust`
.. |P018_typename| replace:: :cyan:`Dust - Sharp GP2Y10`
.. |P018_status| replace:: :green:`NORMAL`
.. |P018_github| replace:: P018_Dust.ino
.. _P018_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P018_Dust.ino
.. |P018_usedby| replace:: `.`
.. |P018_shortinfo| replace:: `.`
.. |P018_maintainer| replace:: `.`
.. |P018_compileinfo| replace:: `.`

.. |P019_name| replace:: :cyan:`PCF8574`
.. |P019_type| replace:: :cyan:`Switch input`
.. |P019_typename| replace:: :cyan:`Switch input - PCF8574`
.. |P019_status| replace:: :green:`NORMAL`
.. |P019_github| replace:: P019_PCF8574.ino
.. _P019_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P019_PCF8574.ino
.. |P019_usedby| replace:: `.`
.. |P019_shortinfo| replace:: `.`
.. |P019_maintainer| replace:: `.`
.. |P019_compileinfo| replace:: `.`

.. |P020_name| replace:: :cyan:`Serial Server`
.. |P020_type| replace:: :cyan:`Communication`
.. |P020_typename| replace:: :cyan:`Communication - Serial Server`
.. |P020_status| replace:: :green:`NORMAL`
.. |P020_github| replace:: P020_Ser2Net.ino
.. _P020_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P020_Ser2Net.ino
.. |P020_usedby| replace:: `.`
.. |P020_shortinfo| replace:: `.`
.. |P020_maintainer| replace:: `.`
.. |P020_compileinfo| replace:: `.`

.. |P021_name| replace:: :cyan:`Level Control`
.. |P021_type| replace:: :cyan:`Regulator`
.. |P021_typename| replace:: :cyan:`Regulator - Level Control`
.. |P021_status| replace:: :green:`NORMAL`
.. |P021_github| replace:: P021_Level.ino
.. _P021_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P021_Level.ino
.. |P021_usedby| replace:: `.`
.. |P021_shortinfo| replace:: `.`
.. |P021_maintainer| replace:: `.`
.. |P021_compileinfo| replace:: `.`

.. |P022_name| replace:: :cyan:`PCA9685`
.. |P022_type| replace:: :cyan:`Extra IO`
.. |P022_typename| replace:: :cyan:`Extra IO - PCA9685`
.. |P022_status| replace:: :green:`NORMAL`
.. |P022_github| replace:: P022_PCA9685.ino
.. _P022_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P022_PCA9685.ino
.. |P022_usedby| replace:: `.`
.. |P022_shortinfo| replace:: `.`
.. |P022_maintainer| replace:: `.`
.. |P022_compileinfo| replace:: `.`

.. |P023_name| replace:: :cyan:`OLED SSD1306`
.. |P023_type| replace:: :cyan:`Display`
.. |P023_typename| replace:: :cyan:`Display - OLED SSD1306`
.. |P023_status| replace:: :green:`NORMAL`
.. |P023_github| replace:: P023_OLED.ino
.. _P023_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P023_OLED.ino
.. |P023_usedby| replace:: `.`
.. |P023_shortinfo| replace:: `.`
.. |P023_maintainer| replace:: `.`
.. |P023_compileinfo| replace:: `.`

.. |P024_name| replace:: :cyan:`MLX90614`
.. |P024_type| replace:: :cyan:`Environment`
.. |P024_typename| replace:: :cyan:`Environment - MLX90614`
.. |P024_status| replace:: :green:`NORMAL`
.. |P024_github| replace:: P024_MLX90614.ino
.. _P024_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P024_MLX90614.ino
.. |P024_usedby| replace:: `.`
.. |P024_shortinfo| replace:: `.`
.. |P024_maintainer| replace:: `.`
.. |P024_compileinfo| replace:: `.`

.. |P025_name| replace:: :cyan:`ADS1115`
.. |P025_type| replace:: :cyan:`Analog input`
.. |P025_typename| replace:: :cyan:`Analog input - ADS1115`
.. |P025_status| replace:: :green:`NORMAL`
.. |P025_github| replace:: P025_ADS1115.ino
.. _P025_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P025_ADS1115.ino
.. |P025_usedby| replace:: `.`
.. |P025_shortinfo| replace:: `.`
.. |P025_maintainer| replace:: `.`
.. |P025_compileinfo| replace:: `.`

.. |P026_name| replace:: :cyan:`System Info`
.. |P026_type| replace:: :cyan:`Generic`
.. |P026_typename| replace:: :cyan:`Generic - System Info`
.. |P026_status| replace:: :green:`NORMAL`
.. |P026_github| replace:: P026_Sysinfo.ino
.. _P026_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P026_Sysinfo.ino
.. |P026_usedby| replace:: `.`
.. |P026_shortinfo| replace:: `.`
.. |P026_maintainer| replace:: `.`
.. |P026_compileinfo| replace:: `.`

.. |P027_name| replace:: :cyan:`INA219`
.. |P027_type| replace:: :cyan:`Energy (DC)`
.. |P027_typename| replace:: :cyan:`Energy (DC) - INA219`
.. |P027_status| replace:: :green:`NORMAL`
.. |P027_github| replace:: P027_INA219.ino
.. _P027_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P027_INA219.ino
.. |P027_usedby| replace:: `.`
.. |P027_shortinfo| replace:: `.`
.. |P027_maintainer| replace:: `.`
.. |P027_compileinfo| replace:: `.`

.. |P028_name| replace:: :cyan:`BMx280`
.. |P028_type| replace:: :cyan:`Environment`
.. |P028_typename| replace:: :cyan:`Environment - BMx280`
.. |P028_status| replace:: :green:`NORMAL`
.. |P028_github| replace:: P028_BME280.ino
.. _P028_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P028_BME280.ino
.. |P028_usedby| replace:: `.`
.. |P028_shortinfo| replace:: `.`
.. |P028_maintainer| replace:: `.`
.. |P028_compileinfo| replace:: `.`

.. |P029_name| replace:: :cyan:`Domoticz MQTT Helper`
.. |P029_type| replace:: :cyan:`Output`
.. |P029_typename| replace:: :cyan:`Output - Domoticz MQTT Helper`
.. |P029_status| replace:: :green:`NORMAL`
.. |P029_github| replace:: P029_Output.ino
.. _P029_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P029_Output.ino
.. |P029_usedby| replace:: `.`
.. |P029_shortinfo| replace:: `.`
.. |P029_maintainer| replace:: `.`
.. |P029_compileinfo| replace:: `.`

.. |P030_name| replace:: :cyan:`BMP280`
.. |P030_type| replace:: :cyan:`Environment`
.. |P030_typename| replace:: :cyan:`Environment - BMP280`
.. |P030_status| replace:: :green:`NORMAL`
.. |P030_github| replace:: P030_BMP280.ino
.. _P030_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P030_BMP280.ino
.. |P030_usedby| replace:: `.`
.. |P030_shortinfo| replace:: `.`
.. |P030_maintainer| replace:: `.`
.. |P030_compileinfo| replace:: `.`

.. |P031_name| replace:: :cyan:`SHT1X`
.. |P031_type| replace:: :cyan:`Environment`
.. |P031_typename| replace:: :cyan:`Environment - SHT1X`
.. |P031_status| replace:: :green:`NORMAL`
.. |P031_github| replace:: P031_SHT1X.ino
.. _P031_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P031_SHT1X.ino
.. |P031_usedby| replace:: `.`
.. |P031_shortinfo| replace:: `.`
.. |P031_maintainer| replace:: `.`
.. |P031_compileinfo| replace:: `.`

.. |P032_name| replace:: :cyan:`MS5611 (GY-63)`
.. |P032_type| replace:: :cyan:`Environment`
.. |P032_typename| replace:: :cyan:`Environment - MS5611 (GY-63)`
.. |P032_status| replace:: :green:`NORMAL`
.. |P032_github| replace:: P032_MS5611.ino
.. _P032_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P032_MS5611.ino
.. |P032_usedby| replace:: `.`
.. |P032_shortinfo| replace:: `.`
.. |P032_maintainer| replace:: `.`
.. |P032_compileinfo| replace:: `.`

.. |P033_name| replace:: :cyan:`Dummy Device`
.. |P033_type| replace:: :cyan:`Generic`
.. |P033_typename| replace:: :cyan:`Generic - Dummy Device`
.. |P033_status| replace:: :green:`NORMAL`
.. |P033_github| replace:: P033_Dummy.ino
.. _P033_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P033_Dummy.ino
.. |P033_usedby| replace:: `.`
.. |P033_shortinfo| replace:: `.`
.. |P033_maintainer| replace:: `.`
.. |P033_compileinfo| replace:: `.`

.. |P034_name| replace:: :cyan:`DHT12 (I2C)`
.. |P034_type| replace:: :cyan:`Environment`
.. |P034_typename| replace:: :cyan:`Environment - DHT12 (I2C)`
.. |P034_status| replace:: :green:`NORMAL`
.. |P034_github| replace:: P034_DHT12.ino
.. _P034_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P034_DHT12.ino
.. |P034_usedby| replace:: `.`
.. |P034_shortinfo| replace:: `.`
.. |P034_maintainer| replace:: `.`
.. |P034_compileinfo| replace:: `.`

.. |P035_name| replace:: :cyan:`IR Transmit`
.. |P035_type| replace:: :cyan:`Communication`
.. |P035_typename| replace:: :cyan:`Communication - IR Transmit`
.. |P035_status| replace:: :green:`NORMAL`
.. |P035_github| replace:: P035_IRTX.ino
.. _P035_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P035_IRTX.ino
.. |P035_usedby| replace:: `.`
.. |P035_shortinfo| replace:: `.`
.. |P035_maintainer| replace:: `.`
.. |P035_compileinfo| replace:: `.`

.. |P036_name| replace:: :cyan:`OLED SSD1306/SH1106 Framed`
.. |P036_type| replace:: :cyan:`Display`
.. |P036_typename| replace:: :cyan:`Display - OLED SSD1306/SH1106 Framed`
.. |P036_status| replace:: :green:`NORMAL`
.. |P036_github| replace:: P036_FrameOLED.ino
.. _P036_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P036_FrameOLED.ino
.. |P036_usedby| replace:: `.`
.. |P036_shortinfo| replace:: `.`
.. |P036_maintainer| replace:: `.`
.. |P036_compileinfo| replace:: `.`

.. |P037_name| replace:: :cyan:`MQTT Import`
.. |P037_type| replace:: :cyan:`Generic`
.. |P037_typename| replace:: :cyan:`Generic - MQTT Import`
.. |P037_status| replace:: :green:`NORMAL`
.. |P037_github| replace:: P037_MQTTImport.ino
.. _P037_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P037_MQTTImport.ino
.. |P037_usedby| replace:: `.`
.. |P037_shortinfo| replace:: `.`
.. |P037_maintainer| replace:: `.`
.. |P037_compileinfo| replace:: `.`

.. |P038_name| replace:: :cyan:`NeoPixel (Basic)`
.. |P038_type| replace:: :cyan:`Output`
.. |P038_typename| replace:: :cyan:`Output - NeoPixel (Basic)`
.. |P038_status| replace:: :green:`NORMAL`
.. |P038_github| replace:: P038_NeoPixel.ino
.. _P038_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P038_NeoPixel.ino
.. |P038_usedby| replace:: `.`
.. |P038_shortinfo| replace:: `.`
.. |P038_maintainer| replace:: `.`
.. |P038_compileinfo| replace:: `.`

.. |P039_name| replace:: :cyan:`Thermocouple`
.. |P039_type| replace:: :cyan:`Environment`
.. |P039_typename| replace:: :cyan:`Environment - Thermocouple`
.. |P039_status| replace:: :green:`NORMAL`
.. |P039_github| replace:: P039_Thermocouple.ino
.. _P039_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P039_Thermocouple.ino
.. |P039_usedby| replace:: `.`
.. |P039_shortinfo| replace:: `.`
.. |P039_maintainer| replace:: `.`
.. |P039_compileinfo| replace:: `.`

.. |P040_name| replace:: :cyan:`ID12LA/RDM6300`
.. |P040_type| replace:: :cyan:`RFID`
.. |P040_typename| replace:: :cyan:`RFID - ID12LA/RDM6300`
.. |P040_status| replace:: :green:`NORMAL`
.. |P040_github| replace:: P040_ID12.ino
.. _P040_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P040_ID12.ino
.. |P040_usedby| replace:: `.`
.. |P040_shortinfo| replace:: `.`
.. |P040_maintainer| replace:: `.`
.. |P040_compileinfo| replace:: `.`

.. |P041_name| replace:: :cyan:`NeoPixel (Word Clock)`
.. |P041_type| replace:: :cyan:`Output`
.. |P041_typename| replace:: :cyan:`Output - NeoPixel (Word Clock)`
.. |P041_status| replace:: :green:`NORMAL`
.. |P041_github| replace:: P041_NeoClock.ino
.. _P041_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P041_NeoClock.ino
.. |P041_usedby| replace:: `.`
.. |P041_shortinfo| replace:: `.`
.. |P041_maintainer| replace:: `.`
.. |P041_compileinfo| replace:: `.`

.. |P042_name| replace:: :cyan:`NeoPixel (Candle)`
.. |P042_type| replace:: :cyan:`Output`
.. |P042_typename| replace:: :cyan:`Output - NeoPixel (Candle)`
.. |P042_status| replace:: :green:`NORMAL`
.. |P042_github| replace:: P042_Candle.ino
.. _P042_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P042_Candle.ino
.. |P042_usedby| replace:: `.`
.. |P042_shortinfo| replace:: `.`
.. |P042_maintainer| replace:: `.`
.. |P042_compileinfo| replace:: `.`

.. |P043_name| replace:: :cyan:`Clock`
.. |P043_type| replace:: :cyan:`Output`
.. |P043_typename| replace:: :cyan:`Output - Clock`
.. |P043_status| replace:: :green:`NORMAL`
.. |P043_github| replace:: P043_ClkOutput.ino
.. _P043_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P043_ClkOutput.ino
.. |P043_usedby| replace:: `.`
.. |P043_shortinfo| replace:: `.`
.. |P043_maintainer| replace:: `.`
.. |P043_compileinfo| replace:: `.`

.. |P044_name| replace:: :cyan:`P1 Wifi Gateway`
.. |P044_type| replace:: :cyan:`Communication`
.. |P044_typename| replace:: :cyan:`Communication - P1 Wifi Gateway`
.. |P044_status| replace:: :green:`NORMAL`
.. |P044_github| replace:: P044_P1WifiGateway.ino
.. _P044_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P044_P1WifiGateway.ino
.. |P044_usedby| replace:: `.`
.. |P044_shortinfo| replace:: `.`
.. |P044_maintainer| replace:: `.`
.. |P044_compileinfo| replace:: `.`

.. |P045_name| replace:: :cyan:`MPU 6050`
.. |P045_type| replace:: :cyan:`Gyro`
.. |P045_typename| replace:: :cyan:`Gyro - MPU 6050`
.. |P045_status| replace:: :yellow:`TESTING`
.. |P045_github| replace:: P045_MPU6050.ino
.. _P045_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P045_MPU6050.ino
.. |P045_usedby| replace:: `.`
.. |P045_shortinfo| replace:: `.`
.. |P045_maintainer| replace:: `.`
.. |P045_compileinfo| replace:: `.`

.. |P046_name| replace:: :cyan:`Ventus W266`
.. |P046_type| replace:: :cyan:`Hardware`
.. |P046_typename| replace:: :cyan:`Hardware - Ventus W266`
.. |P046_status| replace:: :yellow:`TESTING`
.. |P046_github| replace:: P046_VentusW266.ino
.. _P046_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P046_VentusW266.ino
.. |P046_usedby| replace:: `.`
.. |P046_shortinfo| replace:: `.`
.. |P046_maintainer| replace:: `.`
.. |P046_compileinfo| replace:: This one is suppressed by default, you need to compile your own version if you want to use it.

.. |P047_name| replace:: :cyan:`Soil moisture sensor`
.. |P047_type| replace:: :cyan:`Environment`
.. |P047_typename| replace:: :cyan:`Environment - Soil moisture sensor`
.. |P047_status| replace:: :yellow:`TESTING`
.. |P047_github| replace:: P047_i2c-soil-moisture-sensor.ino
.. _P047_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P047_i2c-soil-moisture-sensor.ino
.. |P047_usedby| replace:: `.`
.. |P047_shortinfo| replace:: `.`
.. |P047_maintainer| replace:: `.`
.. |P047_compileinfo| replace:: `.`

.. |P048_name| replace:: :cyan:`Adafruit Motorshield v2`
.. |P048_type| replace:: :cyan:`Motor`
.. |P048_typename| replace:: :cyan:`Motor - Adafruit Motorshield v2`
.. |P048_status| replace:: :yellow:`TESTING`
.. |P048_github| replace:: P048_Motorshield_v2.ino
.. _P048_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P048_Motorshield_v2.ino
.. |P048_usedby| replace:: `.`
.. |P048_shortinfo| replace:: `.`
.. |P048_maintainer| replace:: `.`
.. |P048_compileinfo| replace:: `.`

.. |P049_name| replace:: :cyan:`CO2 MH-Z19`
.. |P049_type| replace:: :cyan:`Gases`
.. |P049_typename| replace:: :cyan:`Gases - CO2 MH-Z19`
.. |P049_status| replace:: :green:`NORMAL`
.. |P049_github| replace:: P049_MHZ19.ino
.. _P049_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P049_MHZ19.ino
.. |P049_usedby| replace:: `.`
.. |P049_shortinfo| replace:: `.`
.. |P049_maintainer| replace:: `.`
.. |P049_compileinfo| replace:: `.`

.. |P050_name| replace:: :cyan:`TCS34725`
.. |P050_type| replace:: :cyan:`Color`
.. |P050_typename| replace:: :cyan:`Color - TCS34725`
.. |P050_status| replace:: :red:`DEVELOPMENT`
.. |P050_github| replace:: P050_TCS34725.ino
.. _P050_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P050_TCS34725.ino
.. |P050_usedby| replace:: `.`
.. |P050_shortinfo| replace:: `.`
.. |P050_maintainer| replace:: `.`
.. |P050_compileinfo| replace:: `.`

.. |P051_name| replace:: :cyan:`AM2320`
.. |P051_type| replace:: :cyan:`Environment`
.. |P051_typename| replace:: :cyan:`Environment - AM2320`
.. |P051_status| replace:: :green:`NORMAL`
.. |P051_github| replace:: P051_AM2320.ino
.. _P051_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P051_AM2320.ino
.. |P051_usedby| replace:: `.`
.. |P051_shortinfo| replace:: `.`
.. |P051_maintainer| replace:: `.`
.. |P051_compileinfo| replace:: `.`

.. |P052_name| replace:: :cyan:`CO2 Senseair`
.. |P052_type| replace:: :cyan:`Gases`
.. |P052_typename| replace:: :cyan:`Gases - CO2 Senseair`
.. |P052_status| replace:: :green:`NORMAL`
.. |P052_github| replace:: P052_SenseAir.ino
.. _P052_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P052_SenseAir.ino
.. |P052_usedby| replace:: :ref:`P052_S8_page`
.. |P052_shortinfo| replace:: The Senseair plugin can be used for multiple gas sensors from the company Senseair. The mostly used sensor is the S8 but other sensor units that work is tSense (K70), K30, K33, S8 (and soon LP8).
.. |P052_maintainer| replace:: `.`
.. |P052_compileinfo| replace:: `.`

.. |P053_name| replace:: :cyan:`PMSx003`
.. |P053_type| replace:: :cyan:`Dust`
.. |P053_typename| replace:: :cyan:`Dust - PMSx003`
.. |P053_status| replace:: :yellow:`TESTING`
.. |P053_github| replace:: P053_PMSx003.ino
.. _P053_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P053_PMSx003.ino
.. |P053_usedby| replace:: `.`
.. |P053_shortinfo| replace:: `.`
.. |P053_maintainer| replace:: `.`
.. |P053_compileinfo| replace:: `.`

.. |P054_name| replace:: :cyan:`DMX512 TX`
.. |P054_type| replace:: :cyan:`Communication`
.. |P054_typename| replace:: :cyan:`Communication - DMX512 TX`
.. |P054_status| replace:: :yellow:`TESTING`
.. |P054_github| replace:: P054_DMX512.ino
.. _P054_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P054_DMX512.ino
.. |P054_usedby| replace:: `.`
.. |P054_shortinfo| replace:: `.`
.. |P054_maintainer| replace:: `.`
.. |P054_compileinfo| replace:: `.`

.. |P055_name| replace:: :cyan:`Chiming`
.. |P055_type| replace:: :cyan:`Notify`
.. |P055_typename| replace:: :cyan:`Notify - Chiming`
.. |P055_status| replace:: :yellow:`TESTING`
.. |P055_github| replace:: P055_Chiming.ino
.. _P055_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P055_Chiming.ino
.. |P055_usedby| replace:: `.`
.. |P055_shortinfo| replace:: `.`
.. |P055_maintainer| replace:: `.`
.. |P055_compileinfo| replace:: `.`

.. |P056_name| replace:: :cyan:`SDS011/018/198`
.. |P056_type| replace:: :cyan:`Dust`
.. |P056_typename| replace:: :cyan:`Dust - SDS011/018/198`
.. |P056_status| replace:: :red:`DEVELOPMENT`
.. |P056_github| replace:: P056_SDS011-Dust.ino
.. _P056_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P056_SDS011-Dust.ino
.. |P056_usedby| replace:: `.`
.. |P056_shortinfo| replace:: `.`
.. |P056_maintainer| replace:: `.`
.. |P056_compileinfo| replace:: `.`

.. |P057_name| replace:: :cyan:`HT16K33`
.. |P057_type| replace:: :cyan:`Display`
.. |P057_typename| replace:: :cyan:`Display - HT16K33`
.. |P057_status| replace:: :yellow:`TESTING`
.. |P057_github| replace:: P057_HT16K33_LED.ino
.. _P057_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P057_HT16K33_LED.ino
.. |P057_usedby| replace:: `.`
.. |P057_shortinfo| replace:: `.`
.. |P057_maintainer| replace:: `.`
.. |P057_compileinfo| replace:: `.`

.. |P058_name| replace:: :cyan:`HT16K33`
.. |P058_type| replace:: :cyan:`Keypad`
.. |P058_typename| replace:: :cyan:`Keypad - HT16K33`
.. |P058_status| replace:: :yellow:`TESTING`
.. |P058_github| replace:: P058_HT16K33_KeyPad.ino
.. _P058_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P058_HT16K33_KeyPad.ino
.. |P058_usedby| replace:: `.`
.. |P058_shortinfo| replace:: `.`
.. |P058_maintainer| replace:: `.`
.. |P058_compileinfo| replace:: `.`

.. |P059_name| replace:: :cyan:`Rotary Encoder`
.. |P059_type| replace:: :cyan:`Switch input`
.. |P059_typename| replace:: :cyan:`Switch input - Rotary Encoder`
.. |P059_status| replace:: :green:`NORMAL`
.. |P059_github| replace:: P059_Encoder.ino
.. _P059_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P059_Encoder.ino
.. |P059_usedby| replace:: `.`
.. |P059_shortinfo| replace:: `.`
.. |P059_maintainer| replace:: `.`
.. |P059_compileinfo| replace:: `.`

.. |P060_name| replace:: :cyan:`MCP3221`
.. |P060_type| replace:: :cyan:`Analog input`
.. |P060_typename| replace:: :cyan:`Analog input - MCP3221`
.. |P060_status| replace:: :yellow:`TESTING`
.. |P060_github| replace:: P060_MCP3221.ino
.. _P060_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P060_MCP3221.ino
.. |P060_usedby| replace:: `.`
.. |P060_shortinfo| replace:: `.`
.. |P060_maintainer| replace:: `.`
.. |P060_compileinfo| replace:: `.`

.. |P061_name| replace:: :cyan:`PCF8574/MCP23017`
.. |P061_type| replace:: :cyan:`Keypad`
.. |P061_typename| replace:: :cyan:`Keypad - PCF8574/MCP23017`
.. |P061_status| replace:: :yellow:`TESTING`
.. |P061_github| replace:: P061_KeyPad.ino
.. _P061_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P061_KeyPad.ino
.. |P061_usedby| replace:: `.`
.. |P061_shortinfo| replace:: `.`
.. |P061_maintainer| replace:: `.`
.. |P061_compileinfo| replace:: `.`

.. |P062_name| replace:: :cyan:`MPR121 Touch`
.. |P062_type| replace:: :cyan:`Keypad`
.. |P062_typename| replace:: :cyan:`Keypad - MPR121 Touch`
.. |P062_status| replace:: :yellow:`TESTING`
.. |P062_github| replace:: P062_MPR121_KeyPad.ino
.. _P062_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P062_MPR121_KeyPad.ino
.. |P062_usedby| replace:: `.`
.. |P062_shortinfo| replace:: `.`
.. |P062_maintainer| replace:: `.`
.. |P062_compileinfo| replace:: `.`

.. |P063_name| replace:: :cyan:`TTP229 Touch`
.. |P063_type| replace:: :cyan:`Keypad`
.. |P063_typename| replace:: :cyan:`Keypad - TTP229 Touch`
.. |P063_status| replace:: :green:`NORMAL`
.. |P063_github| replace:: P063_TTP229_KeyPad.ino
.. _P063_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P063_TTP229_KeyPad.ino
.. |P063_usedby| replace:: `.`
.. |P063_shortinfo| replace:: `.`
.. |P063_maintainer| replace:: `.`
.. |P063_compileinfo| replace:: `.`

.. |P064_name| replace:: :cyan:`APDS9960`
.. |P064_type| replace:: :cyan:`Gesture`
.. |P064_typename| replace:: :cyan:`Gestrure -APDS9960`
.. |P064_status| replace:: :red:`DEVELOPMENT`
.. |P064_github| replace:: P064_APDS9960.ino
.. _P064_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P064_APDS9960.ino
.. |P064_usedby| replace:: `.`
.. |P064_shortinfo| replace:: `.`
.. |P064_maintainer| replace:: `.`
.. |P064_compileinfo| replace:: `.`

.. |P065_name| replace:: :cyan:`DFPlayer-Mini MP3`
.. |P065_type| replace:: :cyan:`Notify`
.. |P065_typename| replace:: :cyan:`Notify - DFPlayer-Mini MP3`
.. |P065_status| replace:: :yellow:`TESTING`
.. |P065_github| replace:: P065_DRF0299_MP3.ino
.. _P065_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P065_DRF0299_MP3.ino
.. |P065_usedby| replace:: `.`
.. |P065_shortinfo| replace:: `.`
.. |P065_maintainer| replace:: `.`
.. |P065_compileinfo| replace:: `.`

.. |P066_name| replace:: :cyan:`VEML6040`
.. |P066_type| replace:: :cyan:`Color`
.. |P066_typename| replace:: :cyan:`Color - VEML6040`
.. |P066_status| replace:: :yellow:`TESTING`
.. |P066_github| replace:: P066_VEML6040.ino
.. _P066_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P066_VEML6040.ino
.. |P066_usedby| replace:: `.`
.. |P066_shortinfo| replace:: `.`
.. |P066_maintainer| replace:: `.`
.. |P066_compileinfo| replace:: `.`

.. |P067_name| replace:: :cyan:`HX711 Load Cell`
.. |P067_type| replace:: :cyan:`Weight`
.. |P067_typename| replace:: :cyan:`Weight - HX711 Load Cell`
.. |P067_status| replace:: :yellow:`TESTING`
.. |P067_github| replace:: P067_HX711_Load_Cell.ino
.. _P067_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P067_HX711_Load_Cell.ino
.. |P067_usedby| replace:: `.`
.. |P067_shortinfo| replace:: `.`
.. |P067_maintainer| replace:: `.`
.. |P067_compileinfo| replace:: `.`

.. |P068_name| replace:: :cyan:`SHT30/31/35`
.. |P068_type| replace:: :cyan:`Environment`
.. |P068_typename| replace:: :cyan:`Environment - SHT30/31/35`
.. |P068_status| replace:: :yellow:`TESTING`
.. |P068_github| replace:: P068_SHT3x.ino
.. _P068_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P068_SHT3x.ino
.. |P068_usedby| replace:: `.`
.. |P068_shortinfo| replace:: `.`
.. |P068_maintainer| replace:: `.`
.. |P068_compileinfo| replace:: `.`

.. |P069_name| replace:: :cyan:`LM75A`
.. |P069_type| replace:: :cyan:`Environment`
.. |P069_typename| replace:: :cyan:`Environment - LM75A`
.. |P069_status| replace:: :yellow:`TESTING`
.. |P069_github| replace:: P069_LM75A.ino
.. _P069_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P069_LM75A.ino
.. |P069_usedby| replace:: `.`
.. |P069_shortinfo| replace:: `.`
.. |P069_maintainer| replace:: `.`
.. |P069_compileinfo| replace:: `.`

.. |P070_name| replace:: :cyan:`NeoPixel Ring Clock`
.. |P070_type| replace:: :cyan:`Output`
.. |P070_typename| replace:: :cyan:`Output -  NeoPixel Ring Clock`
.. |P070_status| replace:: :yellow:`TESTING`
.. |P070_github| replace:: P070_NeoPixel_Clock.ino
.. _P070_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P070_NeoPixel_Clock.ino
.. |P070_usedby| replace:: `.`
.. |P070_shortinfo| replace:: `.`
.. |P070_maintainer| replace:: `.`
.. |P070_compileinfo| replace:: This one is suppressed by default, you need to compile your own version if you want to use it.

.. |P071_name| replace:: :cyan:`Kamstrup Multical 401`
.. |P071_type| replace:: :cyan:`Communication`
.. |P071_typename| replace:: :cyan:`Communication - Kamstrup Multical 401`
.. |P071_status| replace:: :yellow:`TESTING`
.. |P071_github| replace:: P071_Kamstrup401.ino
.. _P071_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P071_Kamstrup401.ino
.. |P071_usedby| replace:: `.`
.. |P071_shortinfo| replace:: `.`
.. |P071_maintainer| replace:: `.`
.. |P071_compileinfo| replace:: `.`

.. |P072_name| replace:: :cyan:`HDC1080 (I2C)`
.. |P072_type| replace:: :cyan:`Environment`
.. |P072_typename| replace:: :cyan:`Environment - HDC1080 (I2C)`
.. |P072_status| replace:: :yellow:`TESTING`
.. |P072_github| replace:: P072_HDC1080.ino
.. _P072_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P072_HDC1080.ino
.. |P072_usedby| replace:: `.`
.. |P072_shortinfo| replace:: `.`
.. |P072_maintainer| replace:: `.`
.. |P072_compileinfo| replace:: `.`

.. |P073_name| replace:: :cyan:`7-segment display`
.. |P073_type| replace:: :cyan:`Display`
.. |P073_typename| replace:: :cyan:`Display - 7-segment display`
.. |P073_status| replace:: :green:`NORMAL`
.. |P073_github| replace:: P073_7DGT.ino
.. _P073_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P073_7DGT.ino
.. |P073_usedby| replace:: `.`
.. |P073_shortinfo| replace:: `.`
.. |P073_maintainer| replace:: `.`
.. |P073_compileinfo| replace:: `.`

.. |P074_name| replace:: :cyan:`TSL2591`
.. |P074_type| replace:: :cyan:`Light/Lux`
.. |P074_typename| replace:: :cyan:`Light/Lux - TSL2591`
.. |P074_status| replace:: :yellow:`TESTING`
.. |P074_github| replace:: P074_TSL2591.ino
.. _P074_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P074_TSL2591.ino
.. |P074_usedby| replace:: `.`
.. |P074_shortinfo| replace:: `.`
.. |P074_maintainer| replace:: `.`
.. |P074_compileinfo| replace:: `.`

.. |P075_name| replace:: :cyan:`Nextion`
.. |P075_type| replace:: :cyan:`Display`
.. |P075_typename| replace:: :cyan:`Display - Nextion`
.. |P075_status| replace:: :yellow:`TESTING`
.. |P075_github| replace:: P075_Nextion.ino
.. _P075_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P075_Nextion.ino
.. |P075_usedby| replace:: `.`
.. |P075_shortinfo| replace:: LCD Color Graphic Touch Screen. Plugin can update display and receive/send touch events.
.. |P075_maintainer| replace:: `.`
.. |P075_compileinfo| replace:: `.`

.. |P076_name| replace:: :cyan:`HLW8012`
.. |P076_type| replace:: :cyan:`Energy (AC)`
.. |P076_typename| replace:: :cyan:`Energy (AC) - HLW8012`
.. |P076_status| replace:: :yellow:`TESTING`
.. |P076_github| replace:: P076_HLW8012.ino
.. _P076_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P076_HLW8012.ino
.. |P076_usedby| replace:: `.`
.. |P076_shortinfo| replace:: `.`
.. |P076_maintainer| replace:: `.`
.. |P076_compileinfo| replace:: `.`

.. |P077_name| replace:: :cyan:`CSE7766`
.. |P077_type| replace:: :cyan:`Energy (AC)`
.. |P077_typename| replace:: :cyan:`Energy (AC) - CSE7766`
.. |P077_status| replace:: :yellow:`TESTING`
.. |P077_github| replace:: P077_CSE7766.ino
.. _P077_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P077_CSE7766.ino
.. |P077_usedby| replace:: `.`
.. |P077_shortinfo| replace:: This plugin is specifically made for Sonoff devices Sonoff S31 and Sonoff Pow R2.
.. |P077_maintainer| replace:: `.`
.. |P077_compileinfo| replace:: `.`

.. |P078_name| replace:: :cyan:`Eastron SDM120C/220T/230/630`
.. |P078_type| replace:: :cyan:`Energy (AC)`
.. |P078_typename| replace:: :cyan:`Energy (AC) - Eastron SDM120C/220T/230/630`
.. |P078_status| replace:: :yellow:`TESTING`
.. |P078_github| replace:: P078_Eastron.ino
.. _P078_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P078_Eastron.ino
.. |P078_usedby| replace:: `.`
.. |P078_shortinfo| replace:: `.`
.. |P078_maintainer| replace:: `.`
.. |P078_compileinfo| replace:: `.`

.. |P079_name| replace:: :cyan:`Wemos Motorshield`
.. |P079_type| replace:: :cyan:`Motor`
.. |P079_typename| replace:: :cyan:`Motor - Wemos Motorshield`
.. |P079_status| replace:: :yellow:`TESTING`
.. |P079_github| replace:: P079_Wemos_Motorshield.ino
.. _P079_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P079_Wemos_Motorshield.ino
.. |P079_usedby| replace:: `.`
.. |P079_shortinfo| replace:: `.`
.. |P079_maintainer| replace:: `.`
.. |P079_compileinfo| replace:: `.`

.. |P080_name| replace:: :cyan:`iButton`
.. |P080_type| replace:: :cyan:`Switch input`
.. |P080_typename| replace:: :cyan:`Switch input - iButton`
.. |P080_status| replace:: :yellow:`TESTING`
.. |P080_github| replace:: P080_DallasIButton.ino
.. _P080_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P080_DallasIButton.ino
.. |P080_usedby| replace:: `.`
.. |P080_shortinfo| replace:: `.`
.. |P080_maintainer| replace:: `.`
.. |P080_compileinfo| replace:: `.`

.. |P081_name| replace:: :cyan:`CRON`
.. |P081_type| replace:: :cyan:`Generic`
.. |P081_typename| replace:: :cyan:`Generic - CRON`
.. |P081_status| replace:: :yellow:`TESTING`
.. |P081_github| replace:: P081_Cron.ino
.. _P081_github: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P081_Cron.ino
.. |P081_usedby| replace:: `.`
.. |P081_shortinfo| replace:: `.`
.. |P081_maintainer| replace:: `.`
.. |P081_compileinfo| replace:: `.`
"""
